### ISSUE TITLE
[BUG] Installing JDBC via Maven Artifact does not work

### ISSUE THREAD

**Issue by ablancolopez** [idealista/keycloak_role#4]
### Description

Installing the JDBC driver required to connect to DB does not work. 

### Steps to Reproduce

For example, with this configuration:
```yaml
keycloak_jdbc_install: true
keycloak_jdbc: ojdbc
keycloak_jdbc_jar: ojdbc8-12.2.01.jar
keycloak_jdbc_file_path: module.xml.j2
keycloak_jdbc_origin: maven
keycloak_jdbc_maven:
  artifact_id: ojdbc8
  group_id: "com.oracle.jdbc"
  version: "12.2.0.1"
  repo_url: "http://my.nexus.repo/repository/maven-oracle/"
```

**Expected behavior:**
Properly installed and working environment

**Actual behavior:**
```An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/opt/keycloak-11.0.3/modules/system/layers/keycloak/org/ojdbc/main/WEB-INF/lib/ojdbc8.jar'```

Seems that the directory does not exist.

**Reproduces how often:** 
Always

### Environment

- The release version/s you are using: 1.0.1, but expect the same bug in all versions.
- OS: Linux
- Ansible Version: Pipfile provided 
- Python Version: Pipfile provided

### Additional Information

Remember that Ansible's maven_artifact needs lxml installed, it can be installed in the role using ```keycloak_additional_libs``` var.
